# Generated by Django 3.0.7 on 2020-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
